sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

script: 
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
  - sbt ++$TRAVIS_SCALA_VERSION -Dakka.test.timefactor=1.5 'set concurrentRestrictions in Global += Tags.limit(Tags.Test, 1)' test
  - sbt ++$TRAVIS_SCALA_VERSION assembly
  - sbt clean coverage test coverageReport
  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm


after_success:
    - bash <(curl -s https://codecov.io/bash)

scala:
  - 2.11.8

codecov:
  token: 7ed31823-191d-476e-b839-72b7e539ad53

jdk:
  - oraclejdk8
  - openjdk8

notifications:
  email:
    - h417652303@gmail.com
