sudo: false

#install:
#    - mvn dependency:resolve
#    - travis_wait 60 mvn install -DskipTests -q

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
  - sbt ++$TRAVIS_SCALA_VERSION -Dakka.test.timefactor=1.5 'set concurrentRestrictions in Global += Tags.limit(Tags.Test, 1)' test
  - sbt ++$TRAVIS_SCALA_VERSION assembly
  - travis_wait 60 sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport
  - find $HOME/.sbt -name "*.lock" | xargs rm

after_success:
  - bash <(curl -s https://codecov.io/bash)

scala:
  - 2.11.12

#  - oraclejdk8
jdk:
  - openjdk8

notifications:
  email:
    - h417652303@gmail.com
