name: Scala CI With Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8.0
      uses: actions/setup-java@v2
      with:
        java-version: '8.0'
        distribution: 'adopt'
    - name: Run tests with Maven
      run: mvn clean test
      
    - name: Run package with Maven
      run: mvn clean package -DskipTests --file pom.xml
